#Definition Namespace für alle Ressourcen
apiVersion: v1
kind: Namespace
metadata:
  name: JSVAR_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicecatalog
  namespace: JSVAR_NAMESPACE
  labels:
    app: servicecatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicecatalog
  template:
    metadata:
      labels:
        app: servicecatalog
    spec:
      containers:
      - name: servicecatalog
        image: JSVAR_DOCKERIMAGE
        env:
        - name: BA_CUSTOMER
          value: JSVAR_BA_CUSTOMER
        - name: BA_DBNAME
          value: JSVAR_BA_DBNAME
        - name: BA_DBUSER
          value: JSVAR_BA_DBUSER
        - name: BA_DBDB
          value: JSVAR_BA_DBDB
        - name: BA_DBPSWD
          value: JSVAR_BA_DBPSWD
        - name: BA_DOMAIN
          value: JSVAR_BA_DOMAIN
        - name: C_NAMESPACE
          value: JSVAR_NAMESPACE
---        
apiVersion: v1
kind: Service
metadata:
  name: servicecatalog-service
  namespace: JSVAR_NAMESPACE
spec:
  type: NodePort
  selector:
    app: servicecatalog
  ports:
  - protocol: TCP
    port: 80      
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: servicecatalog-ingress
  namespace: JSVAR_NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /JSVAR_NAMESPACE/servicecatalog/(.*)
          backend:
            serviceName: servicecatalog-service
            servicePort: 80

